# Universidad Autónoma de Aguascalientes

# Departamento: Ciencias de la Computación

# Carrera: Ingeniería en Computación Inteligente

## Curso: Aprendizaje Automático

## Maestro: Dr. Francisco Javier Luna Rosas

## Alumno: Carlos Leonardo Cruz Ortiz

### Semestre: Enero-Junio del 2026

# PRACTICA No. 4. EL PERCEPTRÓN DE FRANK ROSENBLATT

### El perceptrón es un modelo sencillo de neurona artificial usado para problemas de clasificación binaria. Fue propuesto por Frank Rosenblatt a finales de la década de 1950.

### Un perceptrón toma un conjunto de entradas, las pondera, calcula una suma ponderada y aplica una función de activación (por ejemplo, escalón) para producir una salida.

### Determinar si se aprueba o no una tarjeta de crédito a un cliente, considerando su edad y el ahorro en su cuenta bancaria. En este ejemplo normalizaremos las variables (edad y ahorro) en el rango [0, 1] para simplificar el entrenamiento del perceptrón.

## Paso 1: Importar librerías necesarias

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Paso 2: Generar los datos (DataSet)

In [2]:
personas = np.array([
  [0.3, 0.4], [0.4, 0.3],
  [0.3, 0.2], [0.4, 0.1],
  [0.5, 0.4], [0.4, 0.8],
  [0.6, 0.8], [0.5, 0.6],
  [0.7, 0.6], [0.8, 0.5]
])

## Paso 3: Definir las clases — 1: aprobada, 0: no aprobada

In [3]:
clases = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

## Paso 4: Definir la función de activación

In [ ]:
def activacion(pesos, x, b):
  z = pesos * x
  
  if z.sum() + b > 0:
    return 1
  
  return 0

## Paso 5: Generar pesos y bias (inicialización aleatoria)

In [5]:
pesos = np.random.uniform(-1, 1, size=2)
b = np.random.uniform(-1, 1)
pesos, b, activacion(pesos, [0.8, 0.5], b)

(array([-0.89506147, -0.66289531]), -0.03228565410325923, 0)

## Paso 6: Implementamos el algoritmo del perceptrón

In [ ]:
pesos = np.random.uniform(-1, 1, size=2)
b = np.random.uniform(-1, 1)
tasa_aprendizaje = .01
epocas = 100

# Ciclo de entrenamiento
for epoca in range(epocas):
  error_total = 0
  for i in range(len(personas)):
    prediccion = activacion(pesos, personas[i], b)
    error = clases[i] - prediccion
    error_total += error**2
    pesos[0] += tasa_aprendizaje * personas[i][0] * error
    pesos[1] += tasa_aprendizaje * personas[i][1] * error
    b += tasa_aprendizaje * error
  print(error_total, end=" ")

5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 4 5 4 5 4 3 4 4 3 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

## Paso 7: Probamos el algoritmo

In [10]:
pesos, b, activacion(pesos, [0.3, 0.4], b)

(array([0.1633397 , 0.05946349]), np.float64(-0.11057278441820581), 0)

In [9]:
pesos, b, activacion(pesos, [0.8, 0.5], b)

(array([0.1633397 , 0.05946349]), np.float64(-0.11057278441820581), 1)

## Conclusiones

### En esta practica entrenamos el algoritmo del perceptron para determinar si se le aprueba o no, una tarjeta de credito a un cliente, considerando la edad y el ahorro que tiene en su cuenta bancaria.

## Referencias

### SCIKIT-LEARN (Machine Learning in Python 2025). URL: https://scikit-learn.org/stable/modules/linear_model.html#perceptron (Ultimo acceso febrero 2025).
### Octavio Gutiérrez (2025). El Perceptron Paso a Paso con Python: https://www.youtube.com/watch?v=dkhXGTersPO (Ultimo acceso, Febrero de 2025).
### Sebastian Raschka, Vahid Mirjalili (2019). Machine Learning, Editorial Marcombo, Madrid, Espafia. URL: www.marcombo.info. ISBN: 978-84-267-2720-6